/* =========================================================
 * ====                   WARNING                        ===
 * =========================================================
 * The code in this tab has been generated from the GUI form
 * designer and care should be taken when editing this file.
 * Only add/edit code inside the event handlers i.e. only
 * use lines between the matching comment tags. e.g.

 void myBtnEvents(GButton button) { //_CODE_:button1:12356:
     // It is safe to enter your event code here  
 } //_CODE_:button1:12356:
 
 * Do not rename this tab!
 * =========================================================
 */

synchronized public void win_draw1(PApplet appc, GWinData data) { //_CODE_:GuidingGrowth:415671:
  appc.background(230);
} //_CODE_:GuidingGrowth:415671:

public void EmployeeMonitoringTimeMethod(GCustomSlider source, GEvent event) { //_CODE_:employeeMonitoringTimeVar:570007:
  monitoringTime = employeeMonitoringTimeVar.getValueI();
} //_CODE_:employeeMonitoringTimeVar:570007:

public void collaborationWillingnessMethod(GCustomSlider source, GEvent event) { //_CODE_:collaborationWillingessVar:309765:
  collaborationWillingness = collaborationWillingessVar.getValueI();
} //_CODE_:collaborationWillingessVar:309765:

public void deadlineStrictnessChanged(GCustomSlider source, GEvent event) { //_CODE_:deadlineStrictnessVar:769606:
  deadlineStrictness = deadlineStrictnessVar.getValueI();
} //_CODE_:deadlineStrictnessVar:769606:

public void employeeSalaryChanged(GCustomSlider source, GEvent event) { //_CODE_:employeeSalaryVar:801857:
  employeeSalary = employeeSalaryVar.getValueI();
} //_CODE_:employeeSalaryVar:801857:



// Create all the GUI controls. 
// autogenerated do not edit
public void createGUI(){
  G4P.messagesEnabled(false);
  G4P.setGlobalColorScheme(GCScheme.BLUE_SCHEME);
  G4P.setMouseOverEnabled(false);
  surface.setTitle("Sketch Window");
  GuidingGrowth = GWindow.getWindow(this, "Guiding Growth", 0, 0, 250, 400, JAVA2D);
  GuidingGrowth.noLoop();
  GuidingGrowth.setActionOnClose(G4P.KEEP_OPEN);
  GuidingGrowth.addDrawHandler(this, "win_draw1");
  EmployeeMonitoringTimeVar = new GLabel(GuidingGrowth, 10, 16, 170, 20);
  EmployeeMonitoringTimeVar.setText("Employee Monitoring Time");
  EmployeeMonitoringTimeVar.setOpaque(false);
  employeeMonitoringTimeVar = new GCustomSlider(GuidingGrowth, 11, 37, 230, 40, "grey_blue");
  employeeMonitoringTimeVar.setLimits(10, 10, 30);
  employeeMonitoringTimeVar.setNbrTicks(10);
  employeeMonitoringTimeVar.setNumberFormat(G4P.INTEGER, 0);
  employeeMonitoringTimeVar.setOpaque(false);
  employeeMonitoringTimeVar.addEventHandler(this, "EmployeeMonitoringTimeMethod");
  collaborationWillingnessVar = new GLabel(GuidingGrowth, 9, 99, 177, 20);
  collaborationWillingnessVar.setText("Collaboration Willingess");
  collaborationWillingnessVar.setOpaque(false);
  collaborationWillingessVar = new GCustomSlider(GuidingGrowth, 9, 119, 230, 40, "grey_blue");
  collaborationWillingessVar.setLimits(5, 0, 10);
  collaborationWillingessVar.setNbrTicks(10);
  collaborationWillingessVar.setNumberFormat(G4P.INTEGER, 0);
  collaborationWillingessVar.setOpaque(false);
  collaborationWillingessVar.addEventHandler(this, "collaborationWillingnessMethod");
  deadlineStrictnessText = new GLabel(GuidingGrowth, 8, 188, 181, 20);
  deadlineStrictnessText.setText("Deadline Strictness");
  deadlineStrictnessText.setOpaque(false);
  deadlineStrictnessVar = new GCustomSlider(GuidingGrowth, 10, 208, 230, 40, "grey_blue");
  deadlineStrictnessVar.setLimits(5, 0, 10);
  deadlineStrictnessVar.setNbrTicks(10);
  deadlineStrictnessVar.setNumberFormat(G4P.INTEGER, 0);
  deadlineStrictnessVar.setOpaque(false);
  deadlineStrictnessVar.addEventHandler(this, "deadlineStrictnessChanged");
  employeeSalaryText = new GLabel(GuidingGrowth, 9, 279, 225, 20);
  employeeSalaryText.setText("Employee Salary:");
  employeeSalaryText.setOpaque(false);
  employeeSalaryVar = new GCustomSlider(GuidingGrowth, 9, 301, 225, 40, "grey_blue");
  employeeSalaryVar.setLimits(50000, 45000, 150000);
  employeeSalaryVar.setNumberFormat(G4P.INTEGER, 0);
  employeeSalaryVar.setOpaque(false);
  employeeSalaryVar.addEventHandler(this, "employeeSalaryChanged");
  GuidingGrowth.loop();
}

// Variable declarations 
// autogenerated do not edit
GWindow GuidingGrowth;
GLabel EmployeeMonitoringTimeVar; 
GCustomSlider employeeMonitoringTimeVar; 
GLabel collaborationWillingnessVar; 
GCustomSlider collaborationWillingessVar; 
GLabel deadlineStrictnessText; 
GCustomSlider deadlineStrictnessVar; 
GLabel employeeSalaryText; 
GCustomSlider employeeSalaryVar; 